#!/bin/bash

DIR="."
BIN_DIR="bin"
FILE_CODE="$1"
FILE_LETTER="$2"
TYPE="$3"

if [ "$TYPE" = "1" ] || [ "$TYPE" = "2" ] || [ "$TYPE" = "3" ] || [ "$TYPE" = "4" ]; then
	CONTEST_NO="$4"
	SEARCH_PATH="./contests/div${TYPE}/${CONTEST_NO}"
	FPATH=$(find "$SEARCH_PATH" -type f -name "${FILE_LETTER}*.cpp" | head -n 1)
	FILE=$(basename "$FPATH")
	OUTPUT_NAME=$(basename "${FILE}" .cpp)
	OUTPUT_NAME="${OUTPUT_NAME}_${TYPE}_${CONTEST_NO}"
	BIN_DIR="${BIN_DIR}/div${TYPE}/${CONTEST_NO}"
else
	SEARCH_PATH="D${TYPE}"
	FPATH=$(find "$SEARCH_PATH" -type f -name "${FILE_CODE}${FILE_LETTER}*.cpp" | head -n 1)
	FILE=$(basename "$FPATH")
	OUTPUT_NAME=$(basename "${FILE}" .cpp)
	OUTPUT_NAME="${OUTPUT_NAME}_${TYPE}"
	BIN_DIR="${BIN_DIR}/${TYPE}"
fi

CC="g++"
INCLUDE_DIRS="${DIR}/reqs"
FLAGS="-g -std=c++11 -O2 -Wall"
CCIN="${SEARCH_PATH}/${FILE} -o ${BIN_DIR}/${OUTPUT_NAME}"
CCMD="${CC} ${FLAGS} -I${INCLUDE_DIRS} ${CCIN}"

mkdir -p "${BIN_DIR}"

${CCMD}

if [ $? -eq 0 ]; then
	echo "Complied Successfull"
	echo "Executed ${OUTPUT_NAME}"
	${BIN_DIR}/${OUTPUT_NAME}
else
    echo "Compilation failed."
    exit 1
fi
