#!/bin/bash

DIR="."
FILE_CODE="$1"
FILE_LETTER="$2"
TYPE="$3"

if [ "$TYPE" = "1" ] || [ "$TYPE" = "2" ] || [ "$TYPE" = "3" ] || [ "$TYPE" = "4" ]; then
	CONTEST_NO="$4"
	SEARCH_PATH="./contests/div${TYPE}/${CONTEST_NO}"
	FPATH=$(find "$SEARCH_PATH" -type f -name "${FILE_LETTER}*.cpp" | head -n 1)
	FILE=$(basename "$FPATH")
else
	SEARCH_PATH="D${TYPE}"
	FPATH=$(find "$SEARCH_PATH" -type f -name "${FILE_CODE}${FILE_LETTER}*.cpp" | head -n 1)
	FILE=$(basename "$FPATH")
fi

VIM_FLAGS=("+normal! zR" "+normal G")

vim "${VIM_FLAGS[@]}" "${SEARCH_PATH}/${FILE}"
