#!/bin/bash

FILE_NAME="$1.cpp"
TYPE="$2"

if [ "$TYPE" = "1" ] || [ "$TYPE" = "2" ] || [ "$TYPE" = "3" ] || [ "$TYPE" = "4" ]; then
	CONTEST_NO="$3"
	FILE="./contests/div${TYPE}/${CONTEST_NO}/${FILE_NAME}"
else
	FILE="D${TYPE}/${FILE_NAME}"
fi

REQ_DIR="./reqs/boiler"

STD_TMPL_FILE="${REQ_DIR}/stdtmpl.cpp"
STD_TMPL_CURR=100

VIM_FLAGS="normal! zR"

cp ${STD_TMPL_FILE} ${FILE}
vim +"${STD_TMPL_CURR}" +"${VIM_FLAGS}" ${FILE}
