#!/bin/bash

FILE="$1.cpp"
shift

REQ_DIR="../reqs"

STD_TMPL_FILE="${REQ_DIR}/stdtmpl.cpp"
STD_TMPL_CURR=19

STD_TMPL_TCASE_FILE="${REQ_DIR}/stdtmpl_tcase.cpp"
STD_TMPL_TCASE_CURR=43

STD_TMPL_TNCASE_FILE="${REQ_DIR}/stdtmpl_tncase.cpp"
STD_TMPL_TNCASE_CURR=44

VIM_FLAGS="normal! zR"

if [ "$1" = "-t" ]; then
	cat ${STD_TMPL_TCASE_FILE} > ${FILE}
	vim +"${STD_TMPL_TCASE_CURR}" +"${VIM_FLAGS}" ${FILE}
elif [ "$1" = "-tn" ]; then
	cat ${STD_TMPL_TNCASE_FILE} > ${FILE}
	vim +"${STD_TMPL_TNCASE_CURR}" +"${VIM_FLAGS}" ${FILE}
else
	cat ${STD_TMPL_FILE} > ${FILE}
	vim +"${STD_TMPL_CURR}" +"${VIM_FLAGS}" ${FILE}
fi
